package cz.itnetwork.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

/**
 * <p>This class represents the DTO of an invoice</p>
 * <p>Getters, setters, constructors generated with lombok</p>
 *
 * @author Kat
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class InvoiceDTO {

    /**
     * <p>Represents the id of an invoice</p>
     * <p>Generated by the database in {@link cz.itnetwork.entity.InvoiceEntity}</p>
     * <p>Connects to json property sent from client via {@code @JsonProperty("_id)}</p>
     */
    @JsonProperty("_id")
    private long id;

    /**
     * <p>Represents the invoice number</p>
     * <p>Entered by user</p>
     * <p>Cannot be null</p>
     */
    @NotNull
    private int invoiceNumber;

    /**
     * <p>Represents the date an invoice is issued</p>
     * <p>Entered by user</p>
     * <p>Json property shaped by {@code @JsonFormat as pattern `yyyy-MM-dd`}</p>
     * <p>Cannot be null</p>
     */
    @NotNull
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private Date issued;

    /**
     * <p><Represents the date an invoice is due/p>
     * <p>Entered by user</p>
     * <p>Json property shaped by {@code @JsonFormat as pattern `yyyy-MM-dd`}</p>
     * <p>Cannot be null</p>
     */
    @NotNull
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private Date dueDate;

    /**
     * <p>Represents the name of a product</p>
     * <p>Entered by user</p>
     * <p>Cannot be null</p>
     */
    @NotNull
    private String product;

    /**
     * <p>Represents the price of a product</p>
     * <p>Entered by user</p>
     * <p>Cannot be null, must be positive or 0</p>
     */
    @NotNull
    @PositiveOrZero
    private long price;

    /**
     * <p>Represents the Value Added Tax of a product</p>
     * <p>Entered by user</p>
     * <p>Cannot be null, must be positive or 0</p>
     */
    @NotNull
    @PositiveOrZero
    private int vat;

    /**
     * <p>Represents a note for an invoice</p>
     * <p>Entered by user</p>
     * <p>Can be null</p>
     */
    private String note;

    /**
     * <p>Represents the {@link PersonDTO} of a buyer</p>
     * <p>User sends the id of a person already existing in the database in json object buyer</p>
     * <p>Cannot be null</p>
     */
    @NotNull
    private PersonDTO buyer;

    /**
     * <p>Represents the {@link PersonDTO} of a seller</p>
     * <p>User sends the id of a person already existing in the database in json object seller</p>
     * <p>Cannot be null</p>
     */
    @NotNull
    private PersonDTO seller;
}
