package cz.itnetwork.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.sql.Date;

/**
 * <p>This class represents a database entity (named: invoice) for an invoice</p>
 * <p>Getters, setters generated with lombok</p>
 *
 * @author Kat
 */
@Entity(name = "invoice")
@Getter
@Setter
public class InvoiceEntity {

    /**
     * <p>Represents the id of an invoice</p>
     * <p>Generated by the database</p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /**
     * <p>Represents the number of an invoice</p>
     * <p>Cannot be null</p>
     */
    private int invoiceNumber;

    /**
     * <p>Represents the date an invoice is issued</p>
     * <p>Cannot be null</p>
     */
    @Column(nullable = false)
    private Date issued;

    /**
     * <p>Represents the date an invoice is due</p>
     * <p>Cannot be null</p>
     */
    @Column(nullable = false)
    private Date dueDate;

    /**
     * <p>Represents the name of a product</p>
     * <p>Cannot be null</p>
     */
    @Column(nullable = false)
    private String product;

    /**
     * <p>Represents the price of a product</p>
     * <p>Cannot be null</p>
     */
    private long price;

    /**
     * <p>Represents the Value Added Tax of an invoice</p>
     * <p>Cannot be null</p>
     */
    private int vat;

    /**
     * <p>Represents a note for an invoice</p>
     * <p>Can be null</p>
     */
    @Column(columnDefinition = "TEXT",nullable = true)
    private String note;

    /**
     * <p>Represents the buyer of a product</p>
     * <p>Has a ManyToOne association to invoices (one buyer {@link PersonEntity} can buy many products)</p>
     * <p>Cannot be null</p>
     */
    @ManyToOne
    @JoinColumn(nullable = false)
    private PersonEntity buyer;

    /**
     * <p>Represents the seller of a product</p>
     * <p>Has a ManyToOne association to invoices (one seller {@link PersonEntity} can sell many products)</p>
     * <p>Cannot by null</p>
     */
    @ManyToOne
    @JoinColumn(nullable = false)
    private PersonEntity seller;
}
